/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as DesignRouteImport } from './routes/design'
import { Route as UserRouteImport } from './routes/$user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgChar123loginChar125DotpngRouteImport } from './routes/og/{$login}[.]png'
import { Route as OgCardLoginRouteImport } from './routes/og-card/$login'
import { Route as LoginCliRouteImport } from './routes/login_.cli'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgChar123loginChar125DotpngRoute =
  OgChar123loginChar125DotpngRouteImport.update({
    id: '/og/{$login}.png',
    path: '/og/{$login}.png',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgCardLoginRoute = OgCardLoginRouteImport.update({
  id: '/og-card/$login',
  path: '/og-card/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCliRoute = LoginCliRouteImport.update({
  id: '/login_/cli',
  path: '/login/cli',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/login/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/login/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/login_/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$user'
    | '/design'
    | '/internal'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/login/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$user'
    | '/design'
    | '/internal'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/login/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
  id:
    | '__root__'
    | '/'
    | '/$user'
    | '/design'
    | '/internal'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/login_/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRoute
  DesignRoute: typeof DesignRoute
  InternalRoute: typeof InternalRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  LoginCliRoute: typeof LoginCliRoute
  OgCardLoginRoute: typeof OgCardLoginRoute
  OgChar123loginChar125DotpngRoute: typeof OgChar123loginChar125DotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/{$login}.png': {
      id: '/og/{$login}.png'
      path: '/og/{$login}.png'
      fullPath: '/og/{$login}.png'
      preLoaderRoute: typeof OgChar123loginChar125DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-card/$login': {
      id: '/og-card/$login'
      path: '/og-card/$login'
      fullPath: '/og-card/$login'
      preLoaderRoute: typeof OgCardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/cli': {
      id: '/login_/cli'
      path: '/login/cli'
      fullPath: '/login/cli'
      preLoaderRoute: typeof LoginCliRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRoute,
  DesignRoute: DesignRoute,
  InternalRoute: InternalRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  LoginCliRoute: LoginCliRoute,
  OgCardLoginRoute: OgCardLoginRoute,
  OgChar123loginChar125DotpngRoute: OgChar123loginChar125DotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
